# Problem Set 2.1

## Problem
## Given the LU decomposition A = LU, determine A and |A|:

In [6]:
import numpy as np

class Solution:
    def solver(self, L, U):
        L = np.array(L, dtype="float")
        U = np.array(U, dtype="float")

        A = L @ U
        det = np.linalg.det(A)

        print("A = LU ")
        print(A)
        print(f"|A| = {det:.10f}")

In [7]:
L_a = [
    [1, 0, 0],
    [1, 1, 0],
    [1, 5/3, 1]
]

U_a = [
    [1, 2, 4],
    [0, 3, 21],
    [0, 0, 0]
]


L_b = [
    [2, 0, 0],
    [-1, 1, 0],
    [1, -3, 1]
]

U_b = [
    [2, -1, 1],
    [0, 1, -3],
    [0, 0, 1]
]

In [9]:
# calling the solutions

solution = Solution()
print("2 (a)")
solution.solver(L_a, U_a)
print("2(b)")
solution.solver(L_b, U_b)


2 (a)
A = LU 
[[ 1.  2.  4.]
 [ 1.  5. 25.]
 [ 1.  7. 39.]]
|A| = -0.0000000000
2(b)
A = LU 
[[ 4. -2.  2.]
 [-2.  2. -4.]
 [ 2. -4. 11.]]
|A| = 4.0000000000
