# Problem Set 2.1


### problem 1

# By evaluating the determinant, classify the following matrices as singular, ill con-ditioned, or well conditioned

In [ ]:
import numpy as np


class SolutionToProblem1:
    def classify_matrix(self, A, name):
        A = np.array(A, dtype=float)
        det = np.linalg.det(A)
        cond = np.linalg.cond(A)
        
        print(f"--- Matrix {name} ---")
        print("Matrix:\n", A)
        print(f"Determinant     : {det:.10f}")
        print(f"Condition number: {cond:.2f}")
        
        if abs(det) < 1e-8:
            print("→ **Singular** (Determinant is zero)")
        elif cond > 1000:
            print("→ **Ill-conditioned**")
        else:
            print("→ **Well-conditioned**")
        print()
    

# ==================== Define the Matrices ====================

In [ ]:
# (a)
A = [
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5]
]

# (b)
B = [
    [2.11, -0.80, 1.72],
    [-1.84, 3.03, 1.29],
    [-1.57, 5.25, 4.30]
]

# (c)
C = [
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
]

# (d) 
D = [
    [4, 3, -1],
    [7, -2, 3],
     [5, -18, 13]
]

# ==================== Classify ====================

In [ ]:
solver = SolutionToProblem1()

solver.classify_matrix(A, "(a)")
solver.classify_matrix(B, "(b)")
solver.classify_matrix(C, "(c)")
solver.classify_matrix(D, "(d)")

--- Matrix (a) ---
Matrix:
 [[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
Determinant     : -0.0000000000
Condition number: 40652946335474680.00
→ **Singular** (Determinant is zero)

--- Matrix (b) ---
Matrix:
 [[ 2.11 -0.8   1.72]
 [-1.84  3.03  1.29]
 [-1.57  5.25  4.3 ]]
Determinant     : 0.0588670000
Condition number: 3218.33
→ **Ill-conditioned**

--- Matrix (c) ---
Matrix:
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
Determinant     : 4.0000000000
Condition number: 5.83
→ **Well-conditioned**

--- Matrix (d) ---
Matrix:
 [[  4.   3.  -1.]
 [  7.  -2.   3.]
 [  5. -18.  13.]]
Determinant     : 0.0000000000
Condition number: 56273123201093264.00
→ **Singular** (Determinant is zero)

